In [1]:
import torch
from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")

prompt = "the capital of united states and the capital of france"

tokens = u_tokenizer.encode(prompt)

torch.manual_seed(1)
u_model = UstaModel(vocab_size=len(u_tokenizer.vocab), embedding_dim=4, context_length=32)

sentence_meanings = u_model(tokens)
sentence_meanings.shape

torch.Size([20, 4])

In [2]:
from transformers import Gemma3ForCausalLM

gemma_model = Gemma3ForCausalLM.from_pretrained("google/gemma-3-1b-it")
u_model, gemma_model

c:\Users\Artun\anaconda3\envs\LLM\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


(UstaModel(
   (embedding): Embedding(64, 4)
   (pos_embedding): Embedding(64, 4)
 ),
 Gemma3ForCausalLM(
   (model): Gemma3TextModel(
     (embed_tokens): Gemma3TextScaledWordEmbedding(262144, 1152, padding_idx=0)
     (layers): ModuleList(
       (0-25): 26 x Gemma3DecoderLayer(
         (self_attn): Gemma3Attention(
           (q_proj): Linear(in_features=1152, out_features=1024, bias=False)
           (k_proj): Linear(in_features=1152, out_features=256, bias=False)
           (v_proj): Linear(in_features=1152, out_features=256, bias=False)
           (o_proj): Linear(in_features=1024, out_features=1152, bias=False)
           (q_norm): Gemma3RMSNorm((256,), eps=1e-06)
           (k_norm): Gemma3RMSNorm((256,), eps=1e-06)
         )
         (mlp): Gemma3MLP(
           (gate_proj): Linear(in_features=1152, out_features=6912, bias=False)
           (up_proj): Linear(in_features=1152, out_features=6912, bias=False)
           (down_proj): Linear(in_features=6912, out_features=1152, b

In [3]:
u_tokenizer.tokenize(prompt)

['the',
 ' ',
 'capital',
 ' ',
 'of',
 ' ',
 'united',
 ' ',
 'state',
 's',
 ' ',
 'and',
 ' ',
 'the',
 ' ',
 'capital',
 ' ',
 'of',
 ' ',
 'france']

In [4]:
from plot_tokens import plot_tokens

u_sentences = [
  {
    "words": sentence_meanings.detach().numpy(),
    "labels": u_tokenizer.tokenize(prompt),
    "color": "red",
  },
]

plot_tokens(u_sentences, "Models Context Space")

In [5]:
sentence_meanings

tensor([[-1.5256e+00, -7.5023e-01, -6.5398e-01, -1.6095e+00],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-1.0017e-01, -6.0919e-01, -9.7977e-01, -1.6091e+00],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-7.1214e-01,  3.0372e-01, -7.7731e-01, -2.5146e-01],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-2.2227e-01,  1.6871e+00,  2.2843e-01,  4.6764e-01],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-6.9697e-01, -1.1608e+00,  6.9954e-01,  1.9908e-01],
        [-7.9829e-02,  3.4172e-01,  9.4883e-01, -1.3839e+00],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-1.1102e-01,  2.9274e-01, -1.5785e-01, -2.8787e-02],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-1.5256e+00, -7.5023e-01, -6.5398e-01, -1.6095e+00],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-1.0017e-01, -6.0919e-01, -9.7977e-01, -1.6091e+00],
        

In [6]:
the_pos = [-1.5256, -0.7502, -0.6540, -1.6095]
capital_pos = [ 0.9326, -0.2774,  0.3166, -1.6980]

In [11]:
#burada kelimenin kelime ile olan ilişkileri
# the the ilişkisi
cs_0_0 = sentence_meanings[0][0] * sentence_meanings[0][0] + sentence_meanings[0][1] * sentence_meanings[0][1] + sentence_meanings[0][2] * sentence_meanings[0][2] + sentence_meanings[0][3] * sentence_meanings[0][3]
# the ile boşluk ilişkisi
cs_0_1 = sentence_meanings[0][0] * sentence_meanings[1][0] + sentence_meanings[0][1] * sentence_meanings[1][1] + sentence_meanings[0][2] * sentence_meanings[1][2] + sentence_meanings[0][3] * sentence_meanings[1][3]
#the capital ile benzerliği
cs_0_2 = sentence_meanings[0][0] * sentence_meanings[2][0] + sentence_meanings[0][1] * sentence_meanings[2][1] + sentence_meanings[0][2] * sentence_meanings[2][2] + sentence_meanings[0][3] * sentence_meanings[2][3]
#the ile bir sonraki benzerliği
cs_0_3 = sentence_meanings[0][0] * sentence_meanings[3][0] + sentence_meanings[0][1] * sentence_meanings[3][1] + sentence_meanings[0][2] * sentence_meanings[3][2] + sentence_meanings[0][3] * sentence_meanings[3][3]

cs_0_0, cs_0_1, cs_0_2, cs_0_3

(tensor(5.9084, grad_fn=<AddBackward0>),
 tensor(1.4360, grad_fn=<AddBackward0>),
 tensor(3.8404, grad_fn=<AddBackward0>),
 tensor(1.4360, grad_fn=<AddBackward0>))

In [9]:
total_dist = hardness_dist + brightness_dist + redness_dist + blueness_dist
total_dist

NameError: name 'hardness_dist' is not defined

In [12]:
apple = [-1.5256, -0.7502, -0.6540, -1.6095]
real_apple = [0.5, -0.7502, -0.6540, -1.6095]

In [24]:
def is_apple(pos, real_pos):
  dist1 = pos[0] - real_pos[0]

  print(dist1)

  if dist1 > 0:
    apple[0] -= 0.5
  else:
    apple[0] += 0.5


  return dist1 > 0 and dist1 < 0.5

is_apple(apple, real_apple)


0.47439999999999993


True

In [ ]:
the_pos = [-1.5256, -0.7502, -0.6540, -1.6095]
capital_pos = [0.9326, -0.2774,  0.3166, -1.6980]

In [ ]:
cos_sim_hardness = the_pos[0] * capital_pos[0]
cos_sim_brightness = the_pos[1] * capital_pos[1]
cos_sim_redness = the_pos[2] * capital_pos[2]
cos_sim_blueness = the_pos[3] * capital_pos[3]

total_cos_sim = cos_sim_hardness + cos_sim_brightness + cos_sim_redness + cos_sim_blueness

cos_sim_hardness, cos_sim_brightness, cos_sim_redness, cos_sim_blueness, total_cos_sim

(-1.4227745600000001,
 0.20810547999999998,
 -0.2070564,
 2.7329309999999998,
 1.3112055199999997)

In [ ]:
cs_0_0 = sentence_meanings[0][0] * sentence_meanings[0][0] + sentence_meanings[0][1] * sentence_meanings[0][1] + sentence_meanings[0][2] * sentence_meanings[0][2] + sentence_meanings[0][3] * sentence_meanings[0][3]
cs_0_1 = sentence_meanings[0][0] * sentence_meanings[1][0] + sentence_meanings[0][1] * sentence_meanings[1][1] + sentence_meanings[0][2] * sentence_meanings[1][2] + sentence_meanings[0][3] * sentence_meanings[1][3]
cs_0_2 = sentence_meanings[0][0] * sentence_meanings[2][0] + sentence_meanings[0][1] * sentence_meanings[2][1] + sentence_meanings[0][2] * sentence_meanings[2][2] + sentence_meanings[0][3] * sentence_meanings[2][3]
cs_0_3 = sentence_meanings[0][0] * sentence_meanings[3][0] + sentence_meanings[0][1] * sentence_meanings[3][1] + sentence_meanings[0][2] * sentence_meanings[3][2] + sentence_meanings[0][3] * sentence_meanings[3][3]

cs_0_0, cs_0_1, cs_0_2, cs_0_3

(tensor(5.9084, grad_fn=<AddBackward0>),
 tensor(0.9915, grad_fn=<AddBackward0>),
 tensor(1.3112, grad_fn=<AddBackward0>),
 tensor(-1.0151, grad_fn=<AddBackward0>))

In [ ]:
the_similarities = []

for i in range(sentence_meanings.shape[0]):
  cs_the_i = sentence_meanings[0][0] * sentence_meanings[i][0] + sentence_meanings[0][1] * sentence_meanings[i][1] + sentence_meanings[0][2] * sentence_meanings[i][2] + sentence_meanings[0][3] * sentence_meanings[i][3]
  the_similarities.append(cs_the_i)

the_similarities



[tensor(5.9084, grad_fn=<AddBackward0>),
 tensor(0.9915, grad_fn=<AddBackward0>),
 tensor(1.3112, grad_fn=<AddBackward0>),
 tensor(-1.0151, grad_fn=<AddBackward0>),
 tensor(-0.5984, grad_fn=<AddBackward0>),
 tensor(0.5215, grad_fn=<AddBackward0>),
 tensor(-2.9568, grad_fn=<AddBackward0>),
 tensor(1.3844, grad_fn=<AddBackward0>),
 tensor(3.2495, grad_fn=<AddBackward0>),
 tensor(1.0536, grad_fn=<AddBackward0>),
 tensor(-0.7985, grad_fn=<AddBackward0>),
 tensor(-0.3483, grad_fn=<AddBackward0>),
 tensor(1.3706, grad_fn=<AddBackward0>),
 tensor(3.3436, grad_fn=<AddBackward0>),
 tensor(0.6584, grad_fn=<AddBackward0>),
 tensor(-1.5429, grad_fn=<AddBackward0>),
 tensor(-0.9496, grad_fn=<AddBackward0>),
 tensor(-0.4411, grad_fn=<AddBackward0>),
 tensor(1.0307, grad_fn=<AddBackward0>),
 tensor(-3.9441, grad_fn=<AddBackward0>)]

In [ ]:
all_similarities = torch.zeros(sentence_meanings.shape[0], sentence_meanings.shape[0])
for j in range(sentence_meanings.shape[0]):
  j_similarities = torch.zeros(sentence_meanings.shape[0])

  for i in range(sentence_meanings.shape[0]):
    for k in range(sentence_meanings.shape[1]):
      cs_j_i = sentence_meanings[j][k] * sentence_meanings[i][k]
      j_similarities[i] += cs_j_i

  all_similarities[j] = j_similarities

all_similarities.detach().numpy()

array([[ 5.90842342e+00,  9.91524994e-01,  1.31123888e+00,
        -1.01506197e+00, -5.98358750e-01,  5.21510422e-01,
        -2.95679903e+00,  1.38435686e+00,  3.24948168e+00,
         1.05356205e+00, -7.98454523e-01, -3.48337382e-01,
         1.37064040e+00,  3.34363842e+00,  6.58395648e-01,
        -1.54289484e+00, -9.49555039e-01, -4.41114008e-01,
         1.03069103e+00, -3.94407916e+00],
       [ 9.91524994e-01,  6.48404419e-01, -3.44985247e-01,
        -2.12769225e-01, -8.34367216e-01, -3.59468281e-01,
        -4.32386786e-01,  6.17068112e-01,  9.22347963e-01,
         4.90615070e-01, -5.28138876e-01, -8.62782598e-02,
         2.12269612e-02,  9.08997953e-01,  5.62238276e-01,
        -9.59949076e-01, -4.58646148e-01, -6.07945383e-01,
        -1.72437117e-01, -8.67795944e-01],
       [ 1.31123888e+00, -3.44985247e-01,  3.93028903e+00,
         9.09577966e-01,  3.04722369e-01,  1.50815845e-02,
        -2.63633180e+00, -3.30206811e-01,  6.40884936e-01,
         6.56366348e-02,  9.7

In [ ]:
sentence_meanings.shape, sentence_meanings.T.shape

(torch.Size([20, 4]), torch.Size([4, 20]))

In [ ]:
# Query, Key, Value
all_sim_torch = sentence_meanings @ sentence_meanings.T  #transpozesini al ve çarp 
all_sim_torch

tensor([[ 5.9084e+00,  9.9152e-01,  1.3112e+00, -1.0151e+00, -5.9836e-01,
          5.2151e-01, -2.9568e+00,  1.3844e+00,  3.2495e+00,  1.0536e+00,
         -7.9845e-01, -3.4834e-01,  1.3706e+00,  3.3436e+00,  6.5840e-01,
         -1.5429e+00, -9.4956e-01, -4.4111e-01,  1.0307e+00, -3.9441e+00],
        [ 9.9152e-01,  6.4840e-01, -3.4499e-01, -2.1277e-01, -8.3437e-01,
         -3.5947e-01, -4.3239e-01,  6.1707e-01,  9.2235e-01,  4.9062e-01,
         -5.2814e-01, -8.6278e-02,  2.1227e-02,  9.0900e-01,  5.6224e-01,
         -9.5995e-01, -4.5865e-01, -6.0795e-01, -1.7244e-01, -8.6780e-01],
        [ 1.3112e+00, -3.4499e-01,  3.9303e+00,  9.0958e-01,  3.0472e-01,
          1.5082e-02, -2.6363e+00, -3.3021e-01,  6.4088e-01,  6.5637e-02,
          9.7389e-01, -5.7750e-01, -2.9612e-01,  1.5839e-01,  2.2140e-01,
          1.6721e+00,  1.0830e+00, -8.5442e-01, -1.6800e-01,  1.3312e+00],
        [-1.0151e+00, -2.1277e-01,  9.0958e-01,  6.4840e-01, -3.2971e-02,
         -2.1277e-01, -3.7738e-01, 

In [ ]:
torch.sum(all_sim_torch[0])

tensor(8.2288, grad_fn=<SumBackward0>)

In [ ]:
#her kelimenin önemini içrisindeki bulunma 
attention_weights = torch.softmax(all_similarities, dim=1)
attention_weights

tensor([[8.1946e-01, 5.9999e-03, 8.2603e-03, 8.0667e-04, 1.2237e-03, 3.7499e-03,
         1.1572e-04, 8.8869e-03, 5.7380e-02, 6.3839e-03, 1.0018e-03, 1.5713e-03,
         8.7658e-03, 6.3045e-02, 4.3000e-03, 4.7584e-04, 8.6128e-04, 1.4320e-03,
         6.2396e-03, 4.3116e-05],
        [1.1473e-01, 8.1405e-02, 3.0146e-02, 3.4407e-02, 1.8480e-02, 2.9712e-02,
         2.7623e-02, 7.8894e-02, 1.0706e-01, 6.9522e-02, 2.5101e-02, 3.9047e-02,
         4.3478e-02, 1.0564e-01, 7.4684e-02, 1.6299e-02, 2.6907e-02, 2.3175e-02,
         3.5823e-02, 1.7872e-02],
        [4.4356e-02, 8.4658e-03, 6.0869e-01, 2.9684e-02, 1.6212e-02, 1.2135e-02,
         8.5615e-04, 8.5918e-03, 2.2690e-02, 1.2764e-02, 3.1655e-02, 6.7095e-03,
         8.8897e-03, 1.4005e-02, 1.4916e-02, 6.3631e-02, 3.5306e-02, 5.0865e-03,
         1.0105e-02, 4.5252e-02],
        [1.6006e-02, 3.5703e-02, 1.0968e-01, 8.4471e-02, 4.2736e-02, 3.5703e-02,
         3.0284e-02, 3.0832e-02, 3.1857e-02, 2.4954e-02, 7.2045e-02, 3.7881e-02,
       

In [ ]:
#kelimenin cümle içerisinde ne kadar önemli olduğu * kelimenin kelimeler ile benzerliği
sentence_context_vector = attention_weights @ sentence_meanings # Value
sentence_context_vector, sentence_meanings

(tensor([[-1.3642, -0.5804, -0.6650, -1.4544],
         [-0.3833,  0.0771, -0.3690, -0.4858],
         [ 0.6289, -0.0605,  0.2308, -1.2027],
         [ 0.4327,  0.2193,  0.2051, -0.2858],
         [ 0.0623,  0.3735,  0.4016, -0.1809],
         [-0.2149,  0.1034,  0.1941, -0.2750],
         [-0.0276,  0.8163,  0.2735,  0.6393],
         [-0.4880,  0.0775, -0.4011, -0.5648],
         [-0.8795, -0.4359, -0.5518, -1.0064],
         [-0.6646,  1.0497, -0.8285, -0.8352],
         [ 0.3295,  0.2349,  0.3010, -0.2964],
         [-0.1033,  0.2790,  0.0843, -0.1576],
         [-0.4629,  0.0648, -0.0904, -0.4583],
         [-0.9981,  1.1521, -1.1039, -1.0766],
         [-0.2338,  0.1810, -0.3295, -0.4863],
         [ 0.6268,  1.0575,  0.4230, -0.4987],
         [ 0.4249,  0.2853,  0.2814, -0.3113],
         [-0.1742,  0.2892,  0.3568, -0.0203],
         [-0.3606,  0.1359,  0.0309, -0.3752],
         [ 1.3265,  0.7178,  0.4320, -0.0393]], grad_fn=<MmBackward0>),
 tensor([[-1.5256, -0.7502, -0.6540

In [ ]:
sentence_meanings_without_pos = u_model.embedding(tokens)

In [ ]:
u_sentences = [
  {
    "words": sentence_meanings_without_pos.detach().numpy(),
    "labels": u_tokenizer.tokenize(prompt),
    "color": "blue",
  },
  {
    "words": sentence_meanings.detach().numpy(),
    "labels": u_tokenizer.tokenize(prompt),
    "color": "purple",
  },
  {
    "words": sentence_context_vector.detach().numpy(),
    "labels": u_tokenizer.tokenize(prompt),
    "color": "orange",
  },
]

plot_tokens(u_sentences, "Models Attention Sentence Space")