In [1]:
# the capital of france is paris

prompt = "the capital of the united states is not "

next_token = " "

output = "the capital of france is paris, "

In [2]:
context_length = 12 # gpt-4o 128k, gemma-3-1b 32K

In [3]:
data = "the capital <pad> <pad> <pad> <pad> "
hedef = "capital of <pad> <pad> <pad> <pad> "

In [ ]:
from tokenizer import Tokenizer

tokenizer = Tokenizer("tokenizer.json")

ids = tokenizer.encode(prompt)

len(ids), ids

(16, [0, 61, 1, 61, 2, 61, 0, 61, 3, 61, 4, 58, 61, 5, 61, 6])

In [5]:
# Load model directly
from transformers import AutoTokenizer, Gemma3ForCausalLM

gemma_tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-1b-it")
gemma_model = Gemma3ForCausalLM.from_pretrained("google/gemma-3-1b-it")

gemma_tokenizer.encode(prompt)

[2, 1437, 5279, 529, 506, 26974, 5022, 563, 711, 236743]

In [6]:
gemma_model

Gemma3ForCausalLM(
  (model): Gemma3TextModel(
    (embed_tokens): Gemma3TextScaledWordEmbedding(262144, 1152, padding_idx=0)
    (layers): ModuleList(
      (0-25): 26 x Gemma3DecoderLayer(
        (self_attn): Gemma3Attention(
          (q_proj): Linear(in_features=1152, out_features=1024, bias=False)
          (k_proj): Linear(in_features=1152, out_features=256, bias=False)
          (v_proj): Linear(in_features=1152, out_features=256, bias=False)
          (o_proj): Linear(in_features=1024, out_features=1152, bias=False)
          (q_norm): Gemma3RMSNorm((256,), eps=1e-06)
          (k_norm): Gemma3RMSNorm((256,), eps=1e-06)
        )
        (mlp): Gemma3MLP(
          (gate_proj): Linear(in_features=1152, out_features=6912, bias=False)
          (up_proj): Linear(in_features=1152, out_features=6912, bias=False)
          (down_proj): Linear(in_features=6912, out_features=1152, bias=False)
          (act_fn): GELUTanh()
        )
        (input_layernorm): Gemma3RMSNorm((1152,), e

In [7]:

girdi = "the letter capital of the united states is not"
cikti = "letter capital of the united states is not london"

In [8]:
with open("text.txt", "r") as f:
  text = f.read()

text

'the capital of the united states is not london. the capital of france is paris, and berlin is the capital of germany. rome is in italy, \n\nmadrid is in spain, and lisbon is in portugal. the capital of the united kingdom is not paris, and the capital of the united states is not berlin. \nalthough these places are often mentioned together, although these capitals are often mentioned together, although these are often mentioned together, \neach country has its own capital, and each country has its own city, and each capital has its own identity, and each capital has its own history. washington \nis the capital of the united states, and london is the capital of the united kingdom. paris is known for art and fashion, and berlin is known for art and \nhistory, and rome is known for art and history, and madrid is known for culture and history, and lisbon is known for culture and art. rome is rich with culture, \nrome is rich with history, rome is rich with art, and madrid is rich with art a

In [13]:
token_ids = tokenizer.encode(text)
# save ids

ids_text = ""

for token_id in token_ids:
  ids_text += f"{token_id} "

with open("token_ids.txt", "w") as f:
  f.write(ids_text)


In [14]:
from TextDataset import TextDataset, create_data_loader

stride = 12

train_data_loader = create_data_loader(token_ids, context_length, stride, 1, False)

len(train_data_loader)

132

In [12]:
i = 0
for batch in enumerate(train_data_loader):
  print(batch)
  i += 1
  if i > 2:
    break

(0, [tensor([[ 0, 61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58]]), tensor([[61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58, 61]])])
(1, [tensor([[61,  5, 61,  6, 61,  7, 59, 61,  0, 61,  1, 61]]), tensor([[ 5, 61,  6, 61,  7, 59, 61,  0, 61,  1, 61,  2]])])
(2, [tensor([[ 2, 61,  8, 61,  5, 61,  9, 60, 61, 10, 61, 11]]), tensor([[61,  8, 61,  5, 61,  9, 60, 61, 10, 61, 11, 61]])])


In [15]:
data_iter = iter(train_data_loader)

next(data_iter)

[tensor([[ 0, 61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58]]),
 tensor([[61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58, 61]])]

# Emmbeding sözlük anlamlarının sayısal değerleri

In [17]:
the_1 = 0.1
the_2 = 0.4
the_3 = 0.0
the_4 = 0.0

capital_1 = 0.0
capital_2 = 0.2
capital_3 = 0.24
capital_4 = 0.3

of_1 = 0.10
of_2 = 0.04
of_3 = 0.02
of_4 = 0.01

united_1 = 0.30
united_2 = 0.06
united_3 = 0.03
united_4 = 0.01

In [18]:
dict_v1 = [
  [0.1, 0.0, 0.0, 0.0],
  [0.4, 0.2, 0.04, 0.3],
  [0.0, 0.24, 0.02, 0.01],
  [0.0, 0.0, 0.03, 0.01],
  [0.0, 0.0, 0.0, 0.0]
]

dict_v1[0], dict_v1[1], dict_v1[2], dict_v1[3]

([0.1, 0.0, 0.0, 0.0],
 [0.4, 0.2, 0.04, 0.3],
 [0.0, 0.24, 0.02, 0.01],
 [0.0, 0.0, 0.03, 0.01])

In [19]:
dict_v2 = {
  "the": [0.1, 0.0, 0.0, 0.0],
  "capital": [0.4, 0.2, 0.04, 0.3],
  "of": [0.0, 0.24, 0.02, 0.01],
  "united": [0.0, 0.0, 0.03, 0.01],
  "states": [0.0, 0.0, 0.0, 0.0]
}

dict_v2["the"], dict_v2["capital"], dict_v2["of"], dict_v2["united"], dict_v2["states"]

([0.1, 0.0, 0.0, 0.0],
 [0.4, 0.2, 0.04, 0.3],
 [0.0, 0.24, 0.02, 0.01],
 [0.0, 0.0, 0.03, 0.01],
 [0.0, 0.0, 0.0, 0.0])

In [30]:
import plotly.graph_objects as go
import plotly.io as pio

pio.renderers.default = "vscode"


def plot_dots(sentences_data, title, dims=[0,1,2]):
    traces = []
    for s in sentences_data:
        traces.append(
            go.Scatter3d(
                x=s["words"][:, dims[0]],
                y=s["words"][:, dims[1]],
                z=s["words"][:, dims[2]],
                mode="markers+text",
                marker=dict(size=6, color=s["color"]),
                text=s["labels"],
                hoverinfo="text",
            )
        )

    fig = go.Figure(
        data=traces,
        layout=go.Layout(
            scene=dict(
                xaxis_title="Sertlik",
                yaxis_title="Parlaklık",
                zaxis_title="Kırmızılık",
            ),
            title=title,
        ),
    )
    fig.show(config={"displaylogo": False})
    return fig


In [ ]:
import numpy as np

sentences = [
  {
    "words": np.array([
      [0.1, 0.20, 0.23, 0.0],
      [0.4, 0.2, 0.04, 0.3],
      [0.12, 0.24, 0.2, 0.01],
      [0.0, 0.0, 0.3, 0.01],
      [0.0, 0.0, 0.0, 0.0]
    ]),
    "labels": ["the", "capital", "of", "united", "states"],
    "color": "red",
  },
  {
    "words": np.array([
      [0.4, 0.2, 0.04, 0.3],
      [0.12, 0.24, 0.2, 0.01],
      [0.0, 0.0, 0.3, 0.01],
      [0.0, 0.0, 0.0, 0.0]
    ]),
    "labels": ["capital", "of", "united", "states"],
    "color": "blue",
  }
]

plot_dots(sentences, "Sözlük V1")

In [32]:
import torch

embeddings = torch.nn.Embedding(num_embeddings=64, embedding_dim=4)

In [33]:
sentence = "the capital of united states and the capital of france"

In [39]:

tokens = tokenizer.encode(sentence)
tokens

[0, 61, 1, 61, 2, 61, 3, 61, 4, 58, 61, 10, 61, 0, 61, 1, 61, 2, 61, 8]

In [38]:
meanings = embeddings(torch.tensor(tokens))
meanings

tensor([[-0.7944,  0.5574,  2.4820,  2.4490],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [ 0.5583, -0.5334, -1.3590,  0.5621],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [ 0.5449,  0.4697, -1.0079, -1.0203],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [ 1.4898, -1.7361,  0.4513, -1.4637],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [ 0.7830,  0.6506,  0.0189,  0.3003],
        [ 1.7945,  0.8941, -0.2544, -0.3453],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [-0.5953, -1.5306, -0.8374,  0.1531],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [-0.7944,  0.5574,  2.4820,  2.4490],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [ 0.5583, -0.5334, -1.3590,  0.5621],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [ 0.5449,  0.4697, -1.0079, -1.0203],
        [ 1.1047, -1.1971,  0.5100,  0.8629],
        [ 2.4893, -1.1592, -2.6399, -1.1160]], grad_fn=<EmbeddingBackward0>)

In [ ]:
sentences = [
  {
    "words": meanings.detach().numpy(),
    "labels": tokenizer.tokenize(sentence),
    "color": "red",
  },
]
plot_dots(sentences, "Sözlük V1")

In [40]:
gemma_tokens = gemma_tokenizer.encode(sentence)
gemma_tokens

[2, 1437, 5279, 529, 26974, 5022, 532, 506, 5279, 529, 61034]

In [41]:
gemma_model.model.embed_tokens(torch.tensor(gemma_tokens))


tensor([[ 0.1388, -0.2165, -0.5386,  ..., -0.2465,  0.0267,  0.1258],
        [-0.1668,  1.2761,  0.7914,  ...,  0.6546,  1.1767, -0.4889],
        [ 0.8079,  0.4723,  0.5718,  ...,  0.5138, -0.3190, -0.2579],
        ...,
        [ 0.8079,  0.4723,  0.5718,  ...,  0.5138, -0.3190, -0.2579],
        [ 0.3812,  0.2621,  0.0798,  ...,  0.0192,  0.0074,  0.5883],
        [ 0.1823,  1.0524,  0.0210,  ..., -0.2009, -0.4765, -1.7650]],
       grad_fn=<MulBackward0>)

In [42]:
gemma_meanings = gemma_model.model.embed_tokens(torch.tensor(gemma_tokens))
gemma_meanings.shape

torch.Size([11, 1152])

In [43]:
gemma_tokenizer.tokenize(sentence)

['the',
 '▁capital',
 '▁of',
 '▁united',
 '▁states',
 '▁and',
 '▁the',
 '▁capital',
 '▁of',
 '▁france']

In [44]:

gemma_sentences = [
  {
    "words": gemma_meanings.detach().numpy(),
    "labels": gemma_tokenizer.tokenize(sentence),
    "color": "red",
  },
]
plot_dots(gemma_sentences, "Gemma", dims=[20, 21, 22])