In [12]:
context_length = 32 # gpt-4o 128k, gemma-3-1b 32K

In [13]:
from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

tokenizer = UstaTokenizer("tokenizer.json")

# Emmbeding sözlük anlamlarının sayısal değerleri

In [14]:
the_1 = 0.1
the_2 = 0.4
the_3 = 0.0
the_4 = 0.0

capital_1 = 0.0
capital_2 = 0.2
capital_3 = 0.24
capital_4 = 0.3

of_1 = 0.10
of_2 = 0.04
of_3 = 0.02
of_4 = 0.01

united_1 = 0.30
united_2 = 0.06
united_3 = 0.03
united_4 = 0.01

In [15]:
dict_v1 = [
  [0.1, 0.0, 0.0, 0.0],
  [0.4, 0.2, 0.04, 0.3],
  [0.0, 0.24, 0.02, 0.01],
  [0.0, 0.0, 0.03, 0.01],
  [0.0, 0.0, 0.0, 0.0]
]

dict_v1[0], dict_v1[1], dict_v1[2], dict_v1[3]

([0.1, 0.0, 0.0, 0.0],
 [0.4, 0.2, 0.04, 0.3],
 [0.0, 0.24, 0.02, 0.01],
 [0.0, 0.0, 0.03, 0.01])

In [16]:
dict_v2 = {
  "the": [0.1, 0.0, 0.0, 0.0],
  "capital": [0.4, 0.2, 0.04, 0.3],
  "of": [0.0, 0.24, 0.02, 0.01],
  "united": [0.0, 0.0, 0.03, 0.01],
  "states": [0.0, 0.0, 0.0, 0.0]
}

dict_v2["the"], dict_v2["capital"], dict_v2["of"], dict_v2["united"], dict_v2["states"]

([0.1, 0.0, 0.0, 0.0],
 [0.4, 0.2, 0.04, 0.3],
 [0.0, 0.24, 0.02, 0.01],
 [0.0, 0.0, 0.03, 0.01],
 [0.0, 0.0, 0.0, 0.0])

In [17]:
import plotly.graph_objects as go
import plotly.io as pio

def plot_dots(sentences_data, title, dims=[0,1,2]):
    traces = []
    for s in sentences_data:
        traces.append(
            go.Scatter3d(
                x=s["words"][:, dims[0]],
                y=s["words"][:, dims[1]],
                z=s["words"][:, dims[2]],
                mode="markers+text",
                marker=dict(size=6, color=s["color"]),
                text=s["labels"],
                hoverinfo="text",
            )
        )

    fig = go.Figure(
        data=traces,
        layout=go.Layout(
            scene=dict(
                xaxis_title="Sertlik",
                yaxis_title="Parlaklık",
                zaxis_title="Kırmızılık",
            ),
            title=title,
        ),
    )
    fig.show(config={"displaylogo": False})


In [18]:
import numpy as np

sentences = [
  {
    "words": np.array([
      [0.1, 0.20, 0.23, 0.0],
      [0.4, 0.2, 0.04, 0.3],
      [0.12, 0.24, 0.2, 0.01],
      [0.0, 0.0, 0.3, 0.01],
      [0.0, 0.0, 0.0, 0.0]
    ]),
    "labels": ["the", "capital", "of", "united", "states"],
    "color": "red",
  },
  {
    "words": np.array([
      [0.4, 0.2, 0.04, 0.3],
      [0.12, 0.24, 0.2, 0.01],
      [0.0, 0.0, 0.3, 0.01],
      [0.0, 0.0, 0.0, 0.0]
    ]),
    "labels": ["capital", "of", "united", "states"],
    "color": "blue",
  }
]

plot_dots(sentences, "Sözlük V1")

In [19]:

import torch

torch.manual_seed(1)
embeddings = torch.nn.Embedding(num_embeddings=64, embedding_dim=4)

In [20]:
sentence = "the capital of united states and the capital of france"

In [21]:
sentence1 = "the dog chased the cat"
sentence2 = "the cat chased the dog"

In [22]:
tokens = tokenizer.encode(sentence)
tokens = torch.tensor(tokens)
tokens.shape

C:\Users\Artun\AppData\Local\Temp\ipykernel_28456\3395096202.py:2: UserWarning:

To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).



torch.Size([20])

In [23]:
meanings = embeddings(torch.tensor(tokens))
meanings

C:\Users\Artun\AppData\Local\Temp\ipykernel_28456\2280836142.py:1: UserWarning:

To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).



tensor([[-1.5256e+00, -7.5023e-01, -6.5398e-01, -1.6095e+00],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-1.0017e-01, -6.0919e-01, -9.7977e-01, -1.6091e+00],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-7.1214e-01,  3.0372e-01, -7.7731e-01, -2.5146e-01],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-2.2227e-01,  1.6871e+00,  2.2843e-01,  4.6764e-01],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-6.9697e-01, -1.1608e+00,  6.9954e-01,  1.9908e-01],
        [-7.9829e-02,  3.4172e-01,  9.4883e-01, -1.3839e+00],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-1.1102e-01,  2.9274e-01, -1.5785e-01, -2.8787e-02],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-1.5256e+00, -7.5023e-01, -6.5398e-01, -1.6095e+00],
        [-7.4484e-01, -2.0216e-01, -2.2967e-01,  1.3313e-03],
        [-1.0017e-01, -6.0919e-01, -9.7977e-01, -1.6091e+00],
        

In [24]:
sentences = [
  {
    "words": meanings.detach().numpy(),
    "labels": tokenizer.tokenize(sentence),
    "color": "red",
  },
]
plot_dots(sentences, "Sözlük V1")

In [25]:
# sentence context space

torch.manual_seed(1)
pos_embeddings = torch.nn.Embedding(num_embeddings=context_length, embedding_dim=4)

pos_meanings = pos_embeddings(torch.tensor([i for i in range(tokens.shape[0])]))

pos_meanings.shape

torch.Size([20, 4])

In [26]:
meanings_in_context = meanings + pos_meanings
meanings_in_context.shape

torch.Size([20, 4])

In [27]:
sentences = [
  {
    "words": meanings_in_context.detach().numpy(),
    "labels": tokenizer.tokenize(sentence),
    "color": "red",
  },
]
plot_dots(sentences, "Sentence Context Space")


In [28]:
import math

def get_position_encoding(context_length, embedding_dim, base=10000, device="cpu"):
  p_embeddings = torch.zeros(context_length, embedding_dim, device=device)
  for pos in range(context_length):
    for i in range(embedding_dim // 2):
      p_embeddings[pos, 2 * i] = math.sin(pos / (base ** (2 * i / embedding_dim)))
      if i + 1 < embedding_dim:
        p_embeddings[pos, 2 * i + 1] = math.cos(pos / (base ** (2 * i + 1 / embedding_dim)))
  
  return p_embeddings.unsqueeze(0)    

In [29]:
pos_embeddings = get_position_encoding(20, 4)
pos_embeddings.shape

torch.Size([1, 20, 4])

In [30]:
meanings.shape

torch.Size([20, 4])

In [31]:
meanings_in_sentence = meanings + pos_embeddings
meanings_in_sentence

tensor([[[-1.5256,  0.2498, -0.6540, -0.6095],
         [ 0.0966,  0.7928, -0.2197,  1.0013],
         [ 0.8091,  0.3709, -0.9598, -0.6091],
         [-0.6037,  0.7532, -0.1997,  1.0013],
         [-1.4689,  1.2248, -0.7373,  0.7485],
         [-1.7038,  0.6754, -0.1797,  1.0013],
         [-0.5017,  2.5124,  0.2884,  1.4676],
         [-0.0879,  0.5627, -0.1597,  1.0013],
         [ 0.2924, -0.4641,  0.7795,  1.1991],
         [ 0.3323,  0.9633,  1.0387, -0.3839],
         [-1.2889,  0.3381, -0.1298,  1.0013],
         [-1.1110,  0.7463, -0.0481,  0.9712],
         [-1.2814,  0.1602, -0.1100,  1.0013],
         [-1.1054, -0.4827, -0.5243, -0.6095],
         [ 0.2458, -0.0322, -0.0901,  1.0013],
         [ 0.5501, -0.5385, -0.8303, -0.6091],
         [-1.0327, -0.2314, -0.0703,  1.0013],
         [-1.6735,  0.1749, -0.6081,  0.7485],
         [-1.4958, -0.4294, -0.0506,  1.0013],
         [ 2.0292, -0.3954,  0.3466,  0.2265]]], grad_fn=<AddBackward0>)

In [32]:

sentences = [
  {
    "words": meanings_in_sentence[0].detach().numpy(),
    "labels": tokenizer.tokenize(sentence),
    "color": "red",
  },
  {
    "words": meanings.detach().numpy(),
    "labels": tokenizer.tokenize(sentence),
    "color": "blue",
  },
]
plot_dots(sentences, "Sentence Context Space V2")

In [33]:
def get_rotary_position_encoding(input: torch.Tensor, base=10000, device="cpu"):
  # input: Şeklî (uzunluk, genişlik) olan bir tablo gibi düşün.
  # uzunluk = kaç tane oyuncak var (kaç pozisyon)
  # genişlik = her oyuncağın kaç rengi/özelliği var (boyut)
  context_length, dimension = input.shape

  # Genişlik çift olmalı; çünkü yarısını sağ grup, yarısını sol grup yapacağız
  assert dimension % 2 == 0, "dimension must be even"

  # Genişliğin yarısı (sağ ve sol gruplar için)
  half_dimension = dimension // 2

  # freqs_indices: 0'dan yarıya kadar sayılar (farklı “hızlarda” döndürmek için)
  freqs_indices = torch.arange(0, half_dimension, device=device, dtype=torch.float32)

  # freqs: Her özellik için farklı bir “dönme hızı” (büyüdükçe daha yavaş)
  # base büyük bir sayı; üstler bölündükçe küçük değerler çıkar, frekans gibi davranır
  freqs = 1.0 / (base ** (freqs_indices / dimension))

  # positions: 0, 1, 2, ... gibi sırayla oyuncakların konum numaraları (dike diziyoruz)
  positions = torch.arange(0, context_length, device=device, dtype=torch.float32).unsqueeze(1)

  # angles: Her konum için (pozisyon) ve her hız için (freq) çarpıp bir “açı” elde ediyoruz
  angles = positions * freqs

  # Bu açının sinüs ve kosinüs değerleri: dönme işleminin sihirli tuzu
  sin_angles = torch.sin(angles)
  cos_angles = torch.cos(angles)

  # input'un yarısını “çiftler” (ilk yarı), diğer yarısını “tekler” (ikinci yarı) gibi ayır
  # (Sanki kart destesini ikiye bölmek gibi)
  input_even = input[:, :dimension // 2]  # ilk yarı
  input_odd  = input[:, dimension // 2:]  # ikinci yarı

  # DÖNDÜRME SİHİRİ:
  # x' = x * cos - y * sin
  # y' = x * sin + y * cos
  # Böylece iki yarıyı birbirine göre nazikçe döndürmüş oluyoruz
  input_even_rotated = input_even * cos_angles - input_odd * sin_angles
  input_odd_rotated  = input_even * sin_angles + input_odd * cos_angles
  
  # Aynı boyutta boş bir kutu hazırlıyoruz, içine döndürülmüş halleri koyacağız
  input_rotated = torch.empty_like(input)

  # İlk yarıya döndürülmüş “çiftler”, ikinci yarıya döndürülmüş “tekler” gider
  input_rotated[:, :dimension // 2] = input_even_rotated
  input_rotated[:, dimension // 2:] = input_odd_rotated

  # Ve döndürülmüş renkli oyuncaklarımızı geri veriyoruz :)
  return input_rotated


In [34]:
torch.manual_seed(1)
random_input = torch.randn(context_length, 4)

pos_rotary_encodings = get_rotary_position_encoding(random_input)
pos_rotary_encodings

tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
        [ 0.7703, -0.4455, -0.6137, -1.6619],
        [ 1.0032,  0.3476, -0.3241, -0.1861],
        [ 0.1878,  1.4736, -0.2575,  0.9453],
        [ 0.9850, -1.1467,  0.0702, -0.2687],
        [-0.3901, -0.1726, -1.0182,  0.8257],
        [ 0.4304,  0.6715, -2.4639, -1.2932],
        [ 0.5704, -0.3877, -0.5615, -0.4986],
        [-0.4295,  0.5046,  1.8364, -0.5906],
        [-0.2444,  0.4010, -0.0573, -0.2599],
        [ 0.0073,  0.1824,  0.1928,  0.2308],
        [ 1.5852,  0.0908, -2.3501, -1.2102],
        [-0.7470,  0.6049,  0.5535,  0.3497],
        [ 0.2025, -1.8238,  1.3777,  0.9645],
        [ 0.2030,  0.7948,  0.1107,  0.8154],
        [ 0.9969,  0.6845,  3.5316, -0.9203],
        [-0.1472,  1.0350,  0.5783, -0.9935],
        [ 1.6668, -0.0093, -0.2580, -0.0088],
        [-1.2130,  0.8516, -0.1292,  0.0084],
        [-0.5151,  1.1106,  0.3220, -0.2124],
        [ 0.3904, -0.7068, -0.7293, -0.2138],
        [ 0.6421,  0.3909, -1.2941

In [35]:
meanings.shape

torch.Size([20, 4])

In [36]:
meanings_with_pos_encodings = get_rotary_position_encoding(meanings)
meanings_with_pos_encodings, meanings

(tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
         [-0.2092, -0.2013, -0.7509, -0.0189],
         [ 0.9326, -0.2774,  0.3166, -1.6980],
         [ 0.7698, -0.1935,  0.1223, -0.0585],
         [-0.1228,  0.3777,  1.0470, -0.1133],
         [-0.4315, -0.1780,  0.6491, -0.0958],
         [-0.1496,  1.1284,  0.2814,  1.3386],
         [-0.4106, -0.1555, -0.6625, -0.1292],
         [-0.5907, -0.9515, -0.7913, -0.6940],
         [-0.3183,  1.2965, -0.8974, -0.5926],
         [ 0.5000, -0.1103,  0.5979, -0.1694],
         [-0.1583,  0.1584,  0.1103,  0.2478],
         [-0.7518, -0.0745,  0.2059, -0.1879],
         [-1.1096,  1.3501, -1.2345, -1.1534],
         [ 0.1257, -0.0357, -0.7692, -0.1990],
         [ 0.7132,  1.5620,  0.6792, -0.7215],
         [ 0.6472,  0.0046,  0.4344, -0.2021],
         [-0.5514,  0.2102,  0.8985,  0.3336],
         [-0.6643,  0.0446,  0.4077, -0.1972],
         [ 1.8345,  0.7552,  0.4377,  0.1818]], grad_fn=<CopySlices>),
 tensor([[-1.5256e+00, -7.5023e-01, 

In [37]:
sentences = [
  {
    "words": meanings_with_pos_encodings.detach().numpy(),
    "labels": tokenizer.tokenize(sentence),
    "color": "red",
  },
  {
    "words": meanings.detach().numpy(),
    "labels": tokenizer.tokenize(sentence),
    "color": "blue",
  },
]

plot_dots(sentences, "Sentence Context Space V3 Rotary Encoding")

Örnek bir model import

In [1]:
import torch

from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")

promt = "the capital of united states and the capital of france"

tokens = u_tokenizer.encode(promt)
tokens = torch.tensor(tokens)

model = UstaModel(vocab_size=len(u_tokenizer.vocab), embedding_dim=4, context_length=32)

model

C:\Users\Artun\AppData\Local\Temp\ipykernel_44444\2436455648.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tokens = torch.tensor(tokens)


UstaModel(
  (embedding): Embedding(64, 4)
  (pos_embedding): Embedding(64, 4)
)